npmAlwaysAuth: true
yarn-offline-mirror: ".yarn-offline-cache"
yarn-offline-mirror-pruning: true
packageExtensions:
  "@babel/cli@*":
    dependencies:
      "@babel/core": "*"
  "@babel/core@*":
    peerDependencies:
      "regenerator-runtime": "*"
      "core-js": "*"
